package org.example.ws.bean;

// default package
// Generated 2013-5-15 13:47:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Facility generated by hbm2java
 */
@Entity
@Table(name = "facility", catalog = "shixun")
public class Facility implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer facId;
	private Integer commId;
	private Boolean isCardSupported;
	private Boolean isSmokeEnable;
	private Boolean isWifiSupported;
	private Boolean isJpanese;
	private Boolean isIvoiceSupported;
	private Boolean isPrivateRoomEnabled;

	@Id
	@Column(name = "fac_id", unique = true, nullable = false)
	public Integer getFacId() {
		return this.facId;
	}

	public void setFacId(Integer facId) {
		this.facId = facId;
	}

	@Column(name = "comm_id")
	public Integer getCommId() {
		return commId;
	}

	public void setCommId(Integer commId) {
		this.commId = commId;
	}

	@Column(name = "isCardSupported")
	public Boolean getIsCardSupported() {
		return this.isCardSupported;
	}

	public void setIsCardSupported(Boolean isCardSupported) {
		this.isCardSupported = isCardSupported;
	}

	@Column(name = "isSmokeEnable")
	public Boolean getIsSmokeEnable() {
		return this.isSmokeEnable;
	}

	public void setIsSmokeEnable(Boolean isSmokeEnable) {
		this.isSmokeEnable = isSmokeEnable;
	}

	@Column(name = "isWifiSupported")
	public Boolean getIsWifiSupported() {
		return this.isWifiSupported;
	}

	public void setIsWifiSupported(Boolean isWifiSupported) {
		this.isWifiSupported = isWifiSupported;
	}

	@Column(name = "isJpanese")
	public Boolean getIsJpanese() {
		return this.isJpanese;
	}

	public void setIsJpanese(Boolean isJpanese) {
		this.isJpanese = isJpanese;
	}

	@Column(name = "isIvoiceSupported")
	public Boolean getIsIvoiceSupported() {
		return this.isIvoiceSupported;
	}

	public void setIsIvoiceSupported(Boolean isIvoiceSupported) {
		this.isIvoiceSupported = isIvoiceSupported;
	}

	@Column(name = "isPrivateRoomEnabled")
	public Boolean getIsPrivateRoomEnabled() {
		return this.isPrivateRoomEnabled;
	}

	public void setIsPrivateRoomEnabled(Boolean isPrivateRoomEnabled) {
		this.isPrivateRoomEnabled = isPrivateRoomEnabled;
	}
}
