package org.example.ws.bean;

// default package
// Generated 2013-5-15 13:47:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Kind generated by hbm2java
 */
@Entity
@Table(name = "kind", catalog = "shixun")
public class Kind implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String kind1;

	private String kind2;

	@Column(name = "kind1", length = 20)
	public String getKind1() {
		return kind1;
		
	}

	public void setKind1(String kind1) {
		this.kind1 = kind1;
	}

	@Column(name = "kind2", length = 20)
	public String getKind2() {
		return kind2;
	}

	public void setKind2(String kind2) {
		this.kind2 = kind2;
	}

}
