package org.example.ws.bean;


// default package
// Generated 2013-5-15 12:37:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "shixun")
public class Region implements java.io.Serializable {

	private RegionId id;

	public Region() {
	}

	public Region(RegionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "region1", column = @Column(name = "region1", length = 20)),
			@AttributeOverride(name = "region2", column = @Column(name = "region2", length = 40)) })
	public RegionId getId() {
		return this.id;
	}

	public void setId(RegionId id) {
		this.id = id;
	}

}
